### ISSUE TITLE
Medium post

### ISSUE THREAD

**Issue by ghost** [bjacobel/piggydash#1]
I like your idea and project. Did you ever write that Medium post with full instructions?

**Comment by grrrizzzz** [comment]
Yea I'd like to see how you did this too!

**Comment by bjacobel** [comment]
Hi!

I never ended up solving the issue of how to capture the Dash's HTTP request before it went to Amazon to my liking, so I haven't been working on or using this project for most of the last year. However, I just bought an [IoT Dash button](https://aws.amazon.com/iotbutton/) which can trigger an AWS Lambda function directly, so I'll be using this code in that way now. I added a little bit of documentation about that to the readme, ping me if you're still interested in more info.

Best of luck!
